# 基础配置
base:
  model: "mmfa"  # 默认模型
  task: "pretraining"  # 预训练任务
  device: "cuda"
  save_path: "./checkpoints"
  seed: 42

# 模型选择及其配置
model_configs:
  csl :
    output_dims: 320
  
  mmfa:  # 默认模型配置
    output_dim: 320
    
  mvts_transformer:
    output_dims: 320
    n_heads: 8
    num_layers: 3
    dim_feedforward: 256
    dropout: 0.1
    pos_encoding: "fixed"  # choice: ["fixed", "learnable"]
    activation: "gelu"  # choice: ["relu", "gelu"]
    norm: "BatchNorm"  # choice: ["BatchNorm", "LayerNorm"]
    freeze: false
    
  ts2vec:
    output_dims:  320
    hidden_dims: 64
    depth: 10
    
  ts_tcc:
    kernel_size: 8
    stride: 1
    output_dims: 320
    dropout: 0.35
    num_classes: 2
    timesteps: 10
    
  t_loss:
    channels: 40
    depth: 10
    reduced_size: 160
    output_dims: 320
    kernel_size: 3

  tnc:
    hidden_size: 100
    kernel_size: 3
    encoding_size: 10

# 优化器配置
optimizer:
  name: "Adam"  # 可选 ["Adam", "RAdam"]
  lr: 1.0e-3
  weight_decay: 0.0
  batch_size: 64
  epochs: 100

  csl:
    T: 0.1
    alpha: 0.0
    l3: 0.0
    l4: 0.0
    batch_size: 16
    optimizer: "Adam"
    lr: 1.0e-2
    l2_reg: 0.0

  mmfa:
    output_dims: 320
    loss:
      cov_loss_w: 25
      std_loss_w: 25
      repr_loss_w: 1
    transformations:
      cgau2:
        model:
          model_name: "ResNet12"
          output_dim: 320
        resize_shape: 224
      RP:
        model:
          model_name: "ResNet12"
          output_dim: 320
        resize_shape: 224
      GADF:
        model:
          model_name: "ResNet12"
          output_dim: 320
        max_channel: 20
      fft:
        model:
          model_name: "ResNet1d"
          output_dim: 320
      weasel:
        model:
          model_name: "LongFormer"
          output_dim: 320
    main_transformation:
      - "default"
      - {}
    data_config:
      max_input_length: 1200
      max_input_dim: 20
    lr: 1.0e-2
    l2_reg: 0.02

  mvts_transformer:
    batch_size: 64
    optimizer: "Adam"  # choice: ["Adam", "RAdam"]
    lr: 1.0e-3
    l2_reg: 0
    epochs: 5
  
  t_loss:
    l2_reg: 0
    epochs: 2  # default: 30
    batch_size: 128
    compared_length: null
    nb_steps: 600
    penalty: null
    early_stopping: null
    lr: 0.001
    nb_random_samples: 10
    negative_penalty: 1
    print_interval: 10

  ts_tcc:
    l2_reg: 0
    epochs: 5
    beta1: 0.9
    beta2: 0.99
    lr: 3.0e-4
    batch_size: 128
    temperature: 0.2
    use_cosine_similarity: true
    jitter_scale_ratio: 0.001
    jitter_ratio: 0.001
    max_seg: 5
  
  ts2vec:
    batch_size: 128
    lr: 1.0e-3
    l2_reg: 0
    epochs: 2  # default: 10

  tnc:
    lr: 1.0e-3
    l2_reg: 5.0e-3
    batch_size: 128
    epochs: 2
    augmentation: 5
    window_size: 30
    mc_sample_size: 40
    w: 0.05

# 训练配置
training:
  print_interval: 10
  evaluate_interval: 1
  save_condition: "True"
  key_metric: "loss"

# 预处理配置
preprocessing:
  mean_mask_length: 3
  masking_ratio: 0.15
  mask_mode: "separate"  # 可选 ["separate", "concurrent"]
  mask_distribution: "geometric"  # 可选 ["geometric", "bernoulli"]
  exclude_feats: null

# 任务特定配置
task_configs:
  evaluator: "svm"